/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef CFG_GPIO_H
#define CFG_GPIO_H

#include <gpio.h>

/* Pad configuration was generated automatically using intelp2m 2.5-149f0c750c */
static const struct pad_config gpio_table[] = {
	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_B ------- */

	/* GPP_B0 - CORE_VID0 */
	_PAD_CFG_STRUCT(GPP_B0, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_B1 - CORE_VID1 */
	_PAD_CFG_STRUCT(GPP_B1, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_B2 - VRALERT# */
	_PAD_CFG_STRUCT(GPP_B2, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_B3 - GPIO */
	PAD_NC(GPP_B3, NONE),

	/* GPP_B4 - GPIO */
	PAD_NC(GPP_B4, NONE),

	/* GPP_B5 - GPIO */
	PAD_NC(GPP_B5, NONE),

	/* GPP_B6 - GPIO */
	PAD_NC(GPP_B6, NONE),

	/* GPP_B7 - GPIO */
	PAD_NC(GPP_B7, NONE),

	/* GPP_B8 - GPIO */
	PAD_NC(GPP_B8, NONE),

	/* GPP_B9 - GPIO */
	PAD_NC(GPP_B9, NONE),

	/* GPP_B10 - GPIO */
	PAD_NC(GPP_B10, NONE),

	/* GPP_B11 - PMCALERT# */
	_PAD_CFG_STRUCT(GPP_B11, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPP_B12 - SLP_S0# */
	_PAD_CFG_STRUCT(GPP_B12, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_B13 - PLTRST# */
	_PAD_CFG_STRUCT(GPP_B13, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_B14 - SATA_LED# */
	_PAD_CFG_STRUCT(GPP_B14, PAD_FUNC(NF4) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_B15 - GPIO */
	PAD_NC(GPP_B15, NONE),

	/* GPP_B16 - GPIO */
	PAD_NC(GPP_B16, NONE),

	/* GPP_B17 - GPIO */
	PAD_NC(GPP_B17, NONE),

	/* GPP_B18 - GPIO */
	PAD_CFG_GPO(GPP_B18, 0, PLTRST),

	/* GPP_B19 - GPIO */
	PAD_NC(GPP_B19, NONE),

	/* GPP_B20 - GPIO */
	PAD_NC(GPP_B20, NONE),

	/* GPP_B21 - GPIO */
	PAD_NC(GPP_B21, NONE),

	/* GPP_B22 - GPIO */
	PAD_NC(GPP_B22, NONE),

	/* GPP_B23 - GPIO */
	PAD_CFG_GPO(GPP_B23, 1, PLTRST),

	/* GPP_B24 - GSPI0_CLK_LOOPBK */
	_PAD_CFG_STRUCT(GPP_B24, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_B25 - GSPI1_CLK_LOOPBK */
	_PAD_CFG_STRUCT(GPP_B25, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_BUF(TX_RX_DISABLE), 0),

	/* ------- GPIO Group GPP_T ------- */

	/* GPP_T0 - GPIO */
	PAD_NC(GPP_T0, NONE),

	/* GPP_T1 - GPIO */
	PAD_NC(GPP_T1, NONE),

	/* GPP_T2 - FUSA_DIAGTEST_EN */
	_PAD_CFG_STRUCT(GPP_T2, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(DN_20K)),

	/* GPP_T3 - FUSA_DIAGTEST_MODE */
	_PAD_CFG_STRUCT(GPP_T3, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(DN_20K)),

	/* GPP_T4 - GPIO */
	PAD_NC(GPP_T4, NONE),

	/* GPP_T5 - GPIO */
	PAD_NC(GPP_T5, NONE),

	/* GPP_T6 - GPIO */
	PAD_NC(GPP_T6, NONE),

	/* GPP_T7 - GPIO */
	PAD_NC(GPP_T7, NONE),

	/* GPP_T8 - GPIO */
	PAD_NC(GPP_T8, NONE),

	/* GPP_T9 - GPIO */
	PAD_NC(GPP_T9, NONE),

	/* GPP_T10 - GPIO */
	PAD_NC(GPP_T10, NONE),

	/* GPP_T11 - GPIO */
	PAD_NC(GPP_T11, NONE),

	/* GPP_T12 - GPIO */
	PAD_NC(GPP_T12, NONE),

	/* GPP_T13 - GPIO */
	PAD_NC(GPP_T13, NONE),

	/* GPP_T14 - GPIO */
	PAD_NC(GPP_T14, NONE),

	/* GPP_T15 - GPIO */
	PAD_NC(GPP_T15, NONE),

	/* ------- GPIO Group GPP_A ------- */

	/* GPP_A0 - ESPI_IO0 */
	_PAD_CFG_STRUCT(GPP_A0, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(UP_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A1 - ESPI_IO1 */
	_PAD_CFG_STRUCT(GPP_A1, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A2 - ESPI_IO2 */
	_PAD_CFG_STRUCT(GPP_A2, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(UP_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A3 - ESPI_IO3 */
	_PAD_CFG_STRUCT(GPP_A3, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(UP_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A4 - ESPI_CS0# */
	_PAD_CFG_STRUCT(GPP_A4, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(UP_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A5 - ESPI_ALERT0# */
	_PAD_CFG_STRUCT(GPP_A5, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPP_A6 - ESPI_ALERT1# (NF1; OEM sets GPO-high, single eSPI slave) */
	_PAD_CFG_STRUCT(GPP_A6, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPP_A7 - GPIO */
	PAD_CFG_GPO(GPP_A7, 1, PLTRST),

	/* GPP_A8 - GPIO */
	PAD_CFG_GPO(GPP_A8, 1, PLTRST),

	/* GPP_A9 - ESPI_CLK */
	_PAD_CFG_STRUCT(GPP_A9, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(DN_20K) | PAD_IOSSTATE(IGNORE)),

	/* GPP_A10 - ESPI_RESET# */
	_PAD_CFG_STRUCT(GPP_A10, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_A11 - GPIO */
	PAD_CFG_GPO(GPP_A11, 1, PLTRST),	/* TODO(R09A): OEM sets this NC (no native function, unused) - review before adopting */

	/* GPP_A12 - SATAXPCIE1 */
	_PAD_CFG_STRUCT(GPP_A12, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPP_A13 - GPIO */
	PAD_CFG_GPO(GPP_A13, 1, DEEP),

	/* GPP_A14 - USB_OC1# */
	_PAD_CFG_STRUCT(GPP_A14, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_A15 - GPIO */
	PAD_NC(GPP_A15, NONE),

	/* GPP_A16 - USB_OC3# */
	_PAD_CFG_STRUCT(GPP_A16, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_A17 - GPIO */
	PAD_CFG_GPO(GPP_A17, 1, PLTRST),

	/* GPP_A18 - DDSP_HPDB */
	_PAD_CFG_STRUCT(GPP_A18, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(TxDRxE)),

	/* GPP_A19 - DDSP_HPD1 */
	_PAD_CFG_STRUCT(GPP_A19, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(TxDRxE)),

	/* GPP_A20 - GPIO */
	PAD_NC(GPP_A20, NONE),

	/* GPP_A21 - GPIO */
	PAD_CFG_GPI(GPP_A21, NONE, DEEP),	/* was GPI_SCI: storm src, no DSDT handler */

	/* GPP_A22 - GPIO */
	PAD_CFG_GPO(GPP_A22, 1, PLTRST),

	/* GPP_A23 - ESPI_CS1# */
	_PAD_CFG_STRUCT(GPP_A23, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(UP_20K)),

	/* GPP_ESPI_CLK_LOOPBK - GPP_ESPI_CLK_LOOPBK */
	_PAD_CFG_STRUCT(GPP_ESPI_CLK_LOOPBK, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_BUF(TX_RX_DISABLE), 0),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_S ------- */

	/* GPP_S0 - GPIO */
	PAD_NC(GPP_S0, NONE),

	/* GPP_S1 - GPIO */
	PAD_NC(GPP_S1, NONE),

	/* GPP_S2 - GPIO */
	PAD_NC(GPP_S2, NONE),

	/* GPP_S3 - GPIO */
	PAD_NC(GPP_S3, NONE),

	/* GPP_S4 - GPIO */
	PAD_NC(GPP_S4, NONE),

	/* GPP_S5 - GPIO */
	PAD_NC(GPP_S5, NONE),

	/* GPP_S6 - GPIO */
	PAD_NC(GPP_S6, NONE),

	/* GPP_S7 - GPIO */
	PAD_NC(GPP_S7, NONE),

	/* ------- GPIO Group GPP_I ------- */

	/* GPP_I0 - GPIO */
	PAD_NC(GPP_I0, NONE),

	/* GPP_I1 - GPIO */
	PAD_NC(GPP_I1, NONE),

	/* GPP_I2 - GPIO */
	PAD_NC(GPP_I2, NONE),

	/* GPP_I3 - GPIO */
	PAD_NC(GPP_I3, NONE),

	/* GPP_I4 - GPIO */
	PAD_NC(GPP_I4, NONE),

	/* GPP_I5 - GPIO */
	PAD_NC(GPP_I5, NONE),

	/* GPP_I6 - GPIO */
	PAD_NC(GPP_I6, NONE),

	/* GPP_I7 - EMMC_CMD */
	_PAD_CFG_STRUCT(GPP_I7, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I8 - EMMC_DATA0 */
	_PAD_CFG_STRUCT(GPP_I8, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I9 - EMMC_DATA1 */
	_PAD_CFG_STRUCT(GPP_I9, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I10 - EMMC_DATA2 */
	_PAD_CFG_STRUCT(GPP_I10, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I11 - EMMC_DATA3 */
	_PAD_CFG_STRUCT(GPP_I11, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I12 - EMMC_DATA4 */
	_PAD_CFG_STRUCT(GPP_I12, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I13 - EMMC_DATA5 */
	_PAD_CFG_STRUCT(GPP_I13, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I14 - EMMC_DATA6 */
	_PAD_CFG_STRUCT(GPP_I14, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I15 - EMMC_DATA7 */
	_PAD_CFG_STRUCT(GPP_I15, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I16 - EMMC_RCLK */
	_PAD_CFG_STRUCT(GPP_I16, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I17 - EMMC_CLK */
	_PAD_CFG_STRUCT(GPP_I17, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I18 - EMMC_RESET# */
	_PAD_CFG_STRUCT(GPP_I18, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_I19 - GPIO */
	PAD_NC(GPP_I19, NONE),

	/* ------- GPIO Group GPP_H ------- */

	/* GPP_H0 - GPIO */
	PAD_CFG_GPO(GPP_H0, 1, PLTRST),

	/* GPP_H1 - GPIO */
	PAD_CFG_GPO(GPP_H1, 1, PLTRST),

	/* GPP_H2 - GPIO */
	PAD_CFG_GPO(GPP_H2, 1, DEEP),

	/* GPP_H3 - GPIO */
	_PAD_CFG_STRUCT(GPP_H3, PAD_RESET(PLTRST) | PAD_IRQ_ROUTE(IOAPIC) | PAD_RX_POL(INVERT) | PAD_BUF(TX_DISABLE) | (1 << 1), 0),

	/* GPP_H4 - front-panel buzzer (passive piezo), driven by beep.c.
	 * Idle low; mainboard_boot_beep() bit-bangs it for the boot chime.
	 * NOT the legacy PC speaker - SPKR (GPP_B14) is the SATA LED here. */
	PAD_CFG_GPO(GPP_H4, 0, DEEP),

	/* GPP_H5 - GPIO */
	PAD_NC(GPP_H5, NONE),

	/* GPP_H6 - GPIO */
	PAD_NC(GPP_H6, NONE),

	/* GPP_H7 - GPIO */
	PAD_NC(GPP_H7, NONE),

	/* GPP_H8 - GPIO */
	PAD_NC(GPP_H8, NONE),

	/* GPP_H9 - GPIO */
	PAD_NC(GPP_H9, NONE),

	/* GPP_H10 - GPIO */
	PAD_NC(GPP_H10, NONE),

	/* GPP_H11 - GPIO */
	PAD_NC(GPP_H11, NONE),

	/* GPP_H12 - GPIO */
	PAD_NC(GPP_H12, NONE),

	/* GPP_H13 - GPIO */
	PAD_NC(GPP_H13, NONE),

	/* GPP_H14 - GPIO */
	PAD_NC(GPP_H14, NONE),

	/* GPP_H15 - DDPB_CTRLCLK */
	_PAD_CFG_STRUCT(GPP_H15, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_H16 - GPIO */
	PAD_NC(GPP_H16, NONE),

	/* GPP_H17 - DDPB_CTRLDATA */
	_PAD_CFG_STRUCT(GPP_H17, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_H18 - PROC_C10_GATE# */
	_PAD_CFG_STRUCT(GPP_H18, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_H19 - GPIO */
	PAD_CFG_GPI(GPP_H19, NONE, DEEP),	/* was GPI_SCI */

	/* GPP_H20 - GPIO */
	PAD_NC(GPP_H20, NONE),

	/* GPP_H21 - GPIO */
	PAD_NC(GPP_H21, NONE),

	/* GPP_H22 - GPIO */
	PAD_NC(GPP_H22, NONE),

	/* GPP_H23 - SRCCLKREQ5# (NF2): PCIe clkreq for NIC1 (RP#3) */
	PAD_CFG_NF(GPP_H23, NONE, DEEP, NF2),

	/* ------- GPIO Group GPP_D ------- */

	/* GPP_D0 - GPIO */
	PAD_NC(GPP_D0, NONE),

	/* GPP_D1 - GPIO */
	PAD_NC(GPP_D1, NONE),

	/* GPP_D2 - GPIO */
	PAD_NC(GPP_D2, NONE),

	/* GPP_D3 - GPIO */
	PAD_NC(GPP_D3, NONE),

	/* GPP_D4 - GPIO */
	PAD_NC(GPP_D4, NONE),

	/* GPP_D5 - SRCCLKREQ0# */
	_PAD_CFG_STRUCT(GPP_D5, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_D6 - SRCCLKREQ1# */
	_PAD_CFG_STRUCT(GPP_D6, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_D7 - SRCCLKREQ2# */
	_PAD_CFG_STRUCT(GPP_D7, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_D8 - SRCCLKREQ3# */
	_PAD_CFG_STRUCT(GPP_D8, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_D9 - BSSB_LS2_RX */
	_PAD_CFG_STRUCT(GPP_D9, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_D10 - BSSB_LS2_TX */
	_PAD_CFG_STRUCT(GPP_D10, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_D11 - BSSB_LS3_RX */
	_PAD_CFG_STRUCT(GPP_D11, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_D12 - BSSB_LS3_TX */
	_PAD_CFG_STRUCT(GPP_D12, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_D13 - GPIO */
	PAD_CFG_GPI(GPP_D13, NONE, DEEP),	/* was GPI_SCI (dw1) */

	/* GPP_D14 - GPIO */
	PAD_CFG_GPI(GPP_D14, NONE, DEEP),	/* was GPI_SCI (dw1) */

	/* GPP_D15 - GPIO */
	PAD_CFG_GPO(GPP_D15, 1, PLTRST),

	/* GPP_D16 - GPIO */
	PAD_CFG_GPO(GPP_D16, 1, PLTRST),

	/* GPP_D17 - GPIO */
	PAD_NC(GPP_D17, NONE),

	/* GPP_D18 - GPIO */
	PAD_NC(GPP_D18, NONE),

	/* GPP_D19 - GPIO */
	PAD_NC(GPP_D19, NONE),

	/* GPP_GSPI2_CLK_LOOPBK - GPP_GSPI2_CLK_LOOPBK */
	_PAD_CFG_STRUCT(GPP_GSPI2_CLK_LOOPBK, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_BUF(TX_RX_DISABLE), 0),

	/* ------- GPIO Group vGPIO ------- */

	/* GPP_VGPIO_0 - GPIO */
	PAD_CFG_GPO(GPP_VGPIO_0, 0, DEEP),

	/* GPP_VGPIO_4 - GPIO */
	_PAD_CFG_STRUCT(GPP_VGPIO_4, PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_DISABLE) | (1 << 1), 0),

	/* GPP_VGPIO_5 - GPIO */
	_PAD_CFG_STRUCT(GPP_VGPIO_5, PAD_RESET(DEEP) | (1 << 1) | 1, 0),

	/* GPP_VGPIO_6 - GPP_VGPIO_6 */
	_PAD_CFG_STRUCT(GPP_VGPIO_6, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_7 - GPP_VGPIO_7 */
	PAD_CFG_NF(GPP_VGPIO_7, NONE, DEEP, NF1),

	/* GPP_VGPIO_8 - GPP_VGPIO_8 */
	PAD_CFG_NF(GPP_VGPIO_8, NONE, DEEP, NF1),

	/* GPP_VGPIO_9 - GPP_VGPIO_9 */
	_PAD_CFG_STRUCT(GPP_VGPIO_9, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_10 - GPP_VGPIO_10 */
	_PAD_CFG_STRUCT(GPP_VGPIO_10, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_11 - GPP_VGPIO_11 */
	PAD_CFG_NF(GPP_VGPIO_11, NONE, DEEP, NF1),

	/* GPP_VGPIO_12 - GPP_VGPIO_12 */
	PAD_CFG_NF(GPP_VGPIO_12, NONE, DEEP, NF1),

	/* GPP_VGPIO_13 - GPP_VGPIO_13 */
	_PAD_CFG_STRUCT(GPP_VGPIO_13, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_18 - GPP_VGPIO_18 */
	_PAD_CFG_STRUCT(GPP_VGPIO_18, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_19 - GPP_VGPIO_19 */
	PAD_CFG_NF(GPP_VGPIO_19, NONE, DEEP, NF1),

	/* GPP_VGPIO_20 - GPP_VGPIO_20 */
	PAD_CFG_NF(GPP_VGPIO_20, NONE, DEEP, NF1),

	/* GPP_VGPIO_21 - GPP_VGPIO_21 */
	_PAD_CFG_STRUCT(GPP_VGPIO_21, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_22 - GPP_VGPIO_22 */
	_PAD_CFG_STRUCT(GPP_VGPIO_22, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_23 - GPP_VGPIO_23 */
	PAD_CFG_NF(GPP_VGPIO_23, NONE, DEEP, NF1),

	/* GPP_VGPIO_24 - GPP_VGPIO_24 */
	PAD_CFG_NF(GPP_VGPIO_24, NONE, DEEP, NF1),

	/* GPP_VGPIO_25 - GPP_VGPIO_25 */
	_PAD_CFG_STRUCT(GPP_VGPIO_25, PAD_FUNC(NF1) | PAD_RESET(DEEP) | (1 << 1), 0),

	/* GPP_VGPIO_30 - GPP_VGPIO_30 */
	PAD_CFG_NF(GPP_VGPIO_30, NONE, DEEP, NF1),

	/* GPP_VGPIO_31 - GPP_VGPIO_31 */
	PAD_CFG_NF(GPP_VGPIO_31, NONE, DEEP, NF1),

	/* GPP_VGPIO_32 - GPP_VGPIO_32 */
	PAD_CFG_NF(GPP_VGPIO_32, NONE, DEEP, NF1),

	/* GPP_VGPIO_33 - GPP_VGPIO_33 */
	PAD_CFG_NF(GPP_VGPIO_33, NONE, DEEP, NF1),

	/* GPP_VGPIO_34 - GPP_VGPIO_34 */
	PAD_CFG_NF(GPP_VGPIO_34, NONE, DEEP, NF1),

	/* GPP_VGPIO_35 - GPP_VGPIO_35 */
	PAD_CFG_NF(GPP_VGPIO_35, NONE, DEEP, NF1),

	/* GPP_VGPIO_36 - GPP_VGPIO_36 */
	PAD_CFG_NF(GPP_VGPIO_36, NONE, DEEP, NF1),

	/* GPP_VGPIO_37 - GPP_VGPIO_37 */
	PAD_CFG_NF(GPP_VGPIO_37, NONE, DEEP, NF1),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPP_GPD ------- */

	/* GPD0 - BATLOW# */
	_PAD_CFG_STRUCT(GPD0, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPD1 - ACPRESENT */
	_PAD_CFG_STRUCT(GPD1, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(NATIVE)),

	/* GPD2 - GPIO */
	_PAD_CFG_STRUCT(GPD2, PAD_RESET(DEEP) | PAD_TRIG(EDGE_SINGLE) | PAD_RX_POL(INVERT) | PAD_BUF(TX_DISABLE) | (1 << 1), 0),

	/* GPD3 - PWRBTN# */
	_PAD_CFG_STRUCT(GPD3, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPD4 - SLP_S3# */
	_PAD_CFG_STRUCT(GPD4, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), 0),

	/* GPD5 - SLP_S4# */
	_PAD_CFG_STRUCT(GPD5, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), 0),

	/* GPD6 - SLP_A# */
	_PAD_CFG_STRUCT(GPD6, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), 0),

	/* GPD7 - GPIO */
	PAD_CFG_GPO(GPD7, 1, PLTRST),

	/* GPD8 - SUSCLK */
	_PAD_CFG_STRUCT(GPD8, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPD9 - SLP_WLAN# */
	_PAD_CFG_STRUCT(GPD9, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), 0),

	/* GPD10 - SLP_S5# */
	_PAD_CFG_STRUCT(GPD10, PAD_FUNC(NF1) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), 0),

	/* GPD11 - GPIO */
	PAD_CFG_GPO(GPD11, 0, PWROK),

	/* GPD_INPUT3VSEL - GPD_INPUT3VSEL */
	_PAD_CFG_STRUCT(GPD_INPUT3VSEL, PAD_FUNC(NF1) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPD_SLP_LANB - GPD_SLP_LANB */
	_PAD_CFG_STRUCT(GPD_SLP_LANB, PAD_FUNC(NF1) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPD_SLP_SUSB - GPD_SLP_SUSB */
	_PAD_CFG_STRUCT(GPD_SLP_SUSB, PAD_FUNC(NF1) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPD_WAKEB - GPD_WAKEB */
	_PAD_CFG_STRUCT(GPD_WAKEB, PAD_FUNC(NF1) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPD_DRAM_RESETB - GPD_DRAM_RESETB */
	_PAD_CFG_STRUCT(GPD_DRAM_RESETB, PAD_FUNC(NF1) | PAD_BUF(TX_RX_DISABLE), 0),

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_C ------- */

	/* GPP_C0 - SMBCLK */
	_PAD_CFG_STRUCT(GPP_C0, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_C1 - SMBDATA */
	_PAD_CFG_STRUCT(GPP_C1, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_IOSSTATE(IGNORE)),

	/* GPP_C2 - GPIO */
	PAD_CFG_GPO(GPP_C2, 0, DEEP),

	/* GPP_C3 - SML0CLK */
	_PAD_CFG_STRUCT(GPP_C3, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPP_C4 - SML0DATA */
	_PAD_CFG_STRUCT(GPP_C4, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPP_C5 - GPIO */
	PAD_CFG_GPO(GPP_C5, 0, DEEP),

	/* GPP_C6 - SML1CLK */
	_PAD_CFG_STRUCT(GPP_C6, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPP_C7 - SML1DATA */
	_PAD_CFG_STRUCT(GPP_C7, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), 0),

	/* GPP_C8 - GPIO */
	PAD_NC(GPP_C8, NONE),

	/* GPP_C9 - GPIO */
	PAD_NC(GPP_C9, NONE),

	/* GPP_C10 - GPIO */
	PAD_NC(GPP_C10, NONE),

	/* GPP_C11 - GPIO */
	PAD_NC(GPP_C11, NONE),

	/* GPP_C12 - GPIO */
	PAD_NC(GPP_C12, NONE),

	/* GPP_C13 - GPIO */
	PAD_NC(GPP_C13, NONE),

	/* GPP_C14 - GPIO */
	PAD_NC(GPP_C14, NONE),

	/* GPP_C15 - GPIO */
	PAD_NC(GPP_C15, NONE),

	/* GPP_C16 - GPIO */
	PAD_NC(GPP_C16, NONE),

	/* GPP_C17 - GPIO */
	PAD_NC(GPP_C17, NONE),

	/* GPP_C18 - GPIO */
	PAD_NC(GPP_C18, NONE),

	/* GPP_C19 - GPIO */
	PAD_NC(GPP_C19, NONE),

	/* GPP_C20 - GPIO */
	PAD_NC(GPP_C20, NONE),

	/* GPP_C21 - GPIO */
	PAD_NC(GPP_C21, NONE),

	/* GPP_C22 - GPIO */
	PAD_NC(GPP_C22, NONE),

	/* GPP_C23 - GPIO */
	PAD_NC(GPP_C23, NONE),

	/* ------- GPIO Group GPP_F ------- */

	/* GPP_F0 - CNV_BRI_DT */
	_PAD_CFG_STRUCT(GPP_F0, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_F1 - CNV_BRI_RSP */
	_PAD_CFG_STRUCT(GPP_F1, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPP_F2 - CNV_RGI_DT */
	_PAD_CFG_STRUCT(GPP_F2, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_F3 - CNV_RGI_RSP */
	_PAD_CFG_STRUCT(GPP_F3, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE) | (1 << 1), PAD_PULL(UP_20K)),

	/* GPP_F4 - CNV_RF_RESET# */
	_PAD_CFG_STRUCT(GPP_F4, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_F5 - MODEM_CLKREQ */
	_PAD_CFG_STRUCT(GPP_F5, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_F6 - GPIO */
	PAD_NC(GPP_F6, NONE),

	/* GPP_F7 - GPIO */
	PAD_CFG_GPO(GPP_F7, 0, DEEP),

	/* GPP_F8 - GPIO */
	PAD_NC(GPP_F8, NONE),

	/* GPP_F9 - BOOTMPC */
	_PAD_CFG_STRUCT(GPP_F9, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_F10 - GPIO */
	PAD_CFG_GPO(GPP_F10, 1, PLTRST),

	/* GPP_F11 - GPIO */
	PAD_NC(GPP_F11, NONE),

	/* GPP_F12 - GPIO */
	PAD_NC(GPP_F12, NONE),

	/* GPP_F13 - GPIO */
	_PAD_CFG_STRUCT(GPP_F13, PAD_RESET(PLTRST) | PAD_TRIG(EDGE_SINGLE) | PAD_IRQ_ROUTE(IOAPIC) | PAD_RX_POL(INVERT) | PAD_BUF(TX_DISABLE) | (1 << 1), 0),

	/* GPP_F14 - GPIO */
	PAD_NC(GPP_F14, NONE),

	/* GPP_F15 - GPIO */
	PAD_NC(GPP_F15, NONE),

	/* GPP_F16 - GPIO */
	PAD_CFG_GPO(GPP_F16, 1, PLTRST),

	/* GPP_F17 - GPIO */
	PAD_NC(GPP_F17, NONE),

	/* GPP_F18 - GPIO */
	PAD_NC(GPP_F18, NONE),

	/* GPP_F19 - GPIO */
	PAD_NC(GPP_F19, NONE),

	/* GPP_F20 - Reserved */
	_PAD_CFG_STRUCT(GPP_F20, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_F21 - Reserved */
	_PAD_CFG_STRUCT(GPP_F21, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_F22 - GPIO */
	PAD_NC(GPP_F22, NONE),

	/* GPP_F23 - GPIO */
	PAD_NC(GPP_F23, NONE),

	/* GPP_F_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_F_CLK_LOOPBK, NONE),

	/* ------- GPIO Group GPP_E ------- */

	/* GPP_E0 - GPIO */
	PAD_CFG_NF(GPP_E0, NONE, DEEP, NF1),	/* R09A: SATAXPCIE0 (SATA port-0 detect, AHCI active). v11 had GPI_SCI=storm; NF fixes the storm AND restores the SATA detect our plain-GPI workaround had disabled */

	/* GPP_E1 - GPIO */
	PAD_NC(GPP_E1, NONE),

	/* GPP_E2 - GPIO */
	PAD_NC(GPP_E2, NONE),

	/* GPP_E3 - GPIO */
	PAD_CFG_GPO(GPP_E3, 1, DEEP),

	/* GPP_E4 - GPIO */
	PAD_NC(GPP_E4, NONE),

	/* GPP_E5 - GPIO */
	PAD_CFG_GPO(GPP_E5, 1, PLTRST),

	/* GPP_E6 - GPIO */
	PAD_CFG_GPO(GPP_E6, 0, DEEP),

	/* GPP_E7 - GPIO */
	PAD_NC(GPP_E7, NONE),

	/* GPP_E8 - GPIO */
	PAD_NC(GPP_E8, NONE),

	/* GPP_E9 - GPIO */
	PAD_NC(GPP_E9, NONE),

	/* GPP_E10 - GPIO */
	PAD_NC(GPP_E10, NONE),

	/* GPP_E11 - GPIO */
	PAD_NC(GPP_E11, NONE),

	/* GPP_E12 - GPIO */
	PAD_NC(GPP_E12, NONE),

	/* GPP_E13 - GPIO */
	PAD_NC(GPP_E13, NONE),

	/* GPP_E14 - GPIO */
	PAD_NC(GPP_E14, NONE),

	/* GPP_E15 - Reserved */
	_PAD_CFG_STRUCT(GPP_E15, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_E16 - Reserved */
	_PAD_CFG_STRUCT(GPP_E16, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), 0),

	/* GPP_E17 - GPIO */
	PAD_NC(GPP_E17, NONE),

	/* GPP_E18 - DDP1_CTRLCLK */
	_PAD_CFG_STRUCT(GPP_E18, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE) | PAD_IOSSTATE(HIZCRx0)),

	/* GPP_E19 - DDP1_CTRLDATA */
	_PAD_CFG_STRUCT(GPP_E19, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE) | (1 << 1), PAD_PULL(NATIVE) | PAD_IOSSTATE(HIZCRx0)),

	/* GPP_E20 - BSSB_LS1_RX */
	_PAD_CFG_STRUCT(GPP_E20, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_E21 - BSSB_LS1_TX */
	_PAD_CFG_STRUCT(GPP_E21, PAD_FUNC(NF5) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), PAD_PULL(NATIVE)),

	/* GPP_E22 - DNX_FORCE_RELOAD */
	_PAD_CFG_STRUCT(GPP_E22, PAD_FUNC(NF2) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(DN_20K)),

	/* GPP_E23 - GPIO */
	PAD_CFG_GPO(GPP_E23, 0, DEEP),

	/* GPP_E_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_E_CLK_LOOPBK, NONE),

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_R ------- */

	/* GPP_R0 - HDA_BCLK */
	_PAD_CFG_STRUCT(GPP_R0, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_R1 - HDA_SYNC */
	_PAD_CFG_STRUCT(GPP_R1, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE) | PAD_IOSSTATE(IGNORE)),

	/* GPP_R2 - HDA_SDO */
	_PAD_CFG_STRUCT(GPP_R2, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(RX_DISABLE), PAD_PULL(NATIVE) | PAD_IOSSTATE(IGNORE)),

	/* GPP_R3 - HDA_SDI0 */
	_PAD_CFG_STRUCT(GPP_R3, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_PULL(NATIVE) | PAD_IOSSTATE(IGNORE)),

	/* GPP_R4 - HDA_RST# */
	_PAD_CFG_STRUCT(GPP_R4, PAD_FUNC(NF1) | PAD_RESET(DEEP) | PAD_TRIG(OFF) | PAD_BUF(TX_RX_DISABLE), PAD_IOSSTATE(IGNORE)),

	/* GPP_R5 - GPIO */
	PAD_CFG_GPO(GPP_R5, 1, PLTRST),

	/* GPP_R6 - GPIO */
	PAD_NC(GPP_R6, NONE),

	/* GPP_R7 - GPIO */
	PAD_NC(GPP_R7, NONE),
};

#endif /* CFG_GPIO_H */
